# Generated by Django 5.1.3 on 2024-12-01 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Rating must be between 1 and 5'), django.core.validators.MaxValueValidator(5, message='Rating must be between 1 and 5')]),
        ),
    ]
